### PR TITLE
Update link in Code of Conduct

### PR DESCRIPTION
**Pull request by AevaOnline**
Update the email link for reporting code of conduct incidents, clarify who the recipients are, and replace the word "complaints" with "reports".

Closes issue #37

### CODE REVIEW

**Comment by AevaOnline** [comment]
I believe it's important for the code of conduct documentation to be transparent about the report process. The phrase "community leaders" is vague and obscures who is actually on the receiving end of the conduct@ alias.

If the recipient list is changed in the future, then this document should be updated to reflect the new recipient list.

**Comment by spjohnso** [comment]
If that is your goal... perhaps its better to leave the phrase in Community Leaders and identify who they actually are... as it is not clear from the public website who is actually on the governing board that would receive the complaint. The best list I could find is: https://lists.confidentialcomputing.io/g/governingboard/members but this is the list of people on the GB mailing list.. I don't believe this is the same list of people that get emailed from @conduct.

**Comment by AevaOnline** [comment]
That's a good point, Simon. 

@cetola, can you clarify who the conduct@ alias routes to? Is it governingboard@ or another group, and is there a publicly-visible list of the recipients?

**Comment by MikeCamel** [comment]
Agreed this sits within the GB's remit, though TAC input always helpful (as this time!).

**Pull request merged**
