### PR TITLE
Add Nathaniel McCallum to CODEOWNERS file

### PR DESCRIPTION
**Pull request by Riaankl**
As requested in [TAC SLACK](https://confidentialcomputing.slack.com/archives/C01RAUD2FDF/p1702664802739859)

### CODE REVIEW

**Comment by dcmiddle** [comment]
thanks. github is showing an error that he may not be added to the org with write access for this repo. could you add him please?

**Comment by Riaankl** [comment]
> thanks. github is showing an error that he may not be added to the org with write access for this repo. could you add him please?

I think the issue is two fold, looking at the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) I think both the person making the PR and the person added to the CODEOWNER file need to have at least write permissions on the repo. I am working on getting that sorted out.

**Review by dcmiddle — APPROVED** [review]

**Comment by dcmiddle** [comment]
cc @npmccallum

**Comment by Riaankl** [comment]
@npmccallum you should have received GH invitation. Once excepted this PR should be able to merge.

**Review by yashkmankad — APPROVED** [review]

**Pull request merged**
