### PR TITLE
Create Linux Kernel SIG

### PR DESCRIPTION
**Pull request by dcmiddle**
Proposal to create a working group to bring together kernel and confidential computing subject matter experts with the end goal of better enabling Confidential Computing features in Linux.

### CODE REVIEW

**Comment by thomas-fossati** [comment]
Thanks @dcmiddle for the laudable initiative.

I support it and I would actively participate if this SIG was chartered.

However, I am wondering if this could also be handled (maybe in a more lightweight fashion) as a "liaison" of the existing Attestation SIG.

**Comment by MikeCamel** [comment]
Also in favour.  I think that a separate SIG probably makes sense, as there's definitely work here that's not related to attestation (per @thomas-fossati's comment), and will attract different participants.

**Comment by thomas-fossati** [comment]
> makes sense, as there's definitely work here that's not related to attestation

True, even though my sense is attestation will, at least initially, constitute a big chunk of the discussion, so I expect this SIG would need to coordinate / cross-pollinate / work closely with the Attestation SIG.

**Comment by bonzini** [comment]
Hi all, upstream KVM maintainer here. I'm going to reply to this proposal on the linux-coco mailing list, but please give me a day or two to put together my thoughts coherently.

**Comment by dcmiddle** [comment]
> Hi all, upstream KVM maintainer here. I'm going to reply to this proposal on the linux-coco mailing list, but please give me a day or two to put together my thoughts coherently.

Happy for any and all feedback wherever you would like to provide it!

**Comment by wenhuizhang** [comment]
> > Hi all, upstream KVM maintainer here. I'm going to reply to this proposal on the linux-coco mailing list, but please give me a day or two to put together my thoughts coherently.
> 
> Happy for any and all feedback wherever you would like to provide it!
two kernel communities are involved : (1) COCO for attestation (2) Linux security module for integrity measurement

**Review by yashkmankad — APPROVED** [review]

**Review by lkatalin — APPROVED** [review]

**Comment by dcmiddle** [comment]
Discussion at at the 2023/12/14 meeting of the TAC...
Clarified that this SIG in no way intends to replace, replicate, or change the existing Linux Kernel processes.
Rather it is a forum to discuss new Confidential Computing material (architecture, use cases, emerging standards, etc.) in real-time; bringing together engineers who aren't necessarily in the same technical communities, mail lists, etc.

After discussion the TAC voted to approve this SIG. 
We intend to determine the logistics for the meetings in January and those logistics, like all of our SIGs, will be publicly announced. 
Everyone is welcome to join and contribute.

**Review by sameo — APPROVED** [review]

**Review by cfircohen — APPROVED** [review]
LGTM. SIG is well scoped with minimum viable governance structure.

**Review by djbw — APPROVED** [review]
Looks good to me, would be nice to have a place like this to model the "Code First" flow that works well for open collaboration of EFI/ACPI platform changes.

**Pull request merged**
