### PR TITLE
Added Certifier Framework

### PR DESCRIPTION
**Pull request by bensternthal**
@Riaankl would love an extra set of eyes on this one.

### CODE REVIEW

**Review by Riaankl — APPROVED** [review]
Look good to me.

Don't they have any artwork?

**Comment by dcmiddle** [comment]
Does the charter need to be signed? Veraison has a docusign number in the header for example, but maybe that is an outmoded process?

**Comment by bensternthal** [comment]
@dcmiddle Charter is not signed and the lack of Docusign in the header is a non-issue.

**Review by dcmiddle — APPROVED** [review]
LGTM
cc: @jlmucb

**Pull request merged**
