### PR TITLE
Add mediation to Code of Conduct

### PR DESCRIPTION
**Pull request by dcmiddle**
Per discussion at TAC 2022-02-10 and thread https://lists.confidentialcomputing.io/g/tac/topic/staffing_coc_reporting/89022382

I copied wording [from CNCF for mediation](https://github.com/cncf/foundation/blob/main/code-of-conduct.md#reporting). Mike Dolan was also mentioned during our discussions as a contact for escalation/mediation in cases of conflict of interest. I welcome feedback on the most appropriate LF contact. Once this PR is resolved then we can add similar text to the project submission template so that projects can use this escalation / mediation path as well.

### CODE REVIEW

**Comment by dcmiddle** [comment]
@stephenrwalli please comment if you have any input on the right name for escalation/mediation.

**Comment by dcmiddle** [comment]
cc: @AevaOnline

**Review by dthaler — APPROVED** [review]
I don't know the "correct" LF contact, but have no objections.

**Comment by brianwarner** [comment]
I think we talked about this during the call, but just for the folks who weren't there I'll also document it here as well. For escalation specifically, the best I've seen has been where two individuals are named and either is sufficient to see the process through to completion without the other, so the person doing the escalation has an alternative (with project context) should there be a conflict of interest. I believe it's usually the current governing board chair and the current TAC chair. If both contacts have a conflict of interest, or if the CCC escalation completes and further escalation is deemed necessary, then it goes to Mike Dolan as manager of LF Projects, LLC (as documented in the [default policy](https://lfprojects.org/policies/code-of-conduct/) for projects under Incident Procedure).

**Comment by brianwarner** [comment]
Good points, Dave.

**Review by lkatalin — APPROVED** [review]

**Pull request merged**
